# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import emailservice_pb2 as emailservice__pb2


class EmailServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEmail = channel.unary_unary(
                '/emailservice.EmailService/GetEmail',
                request_serializer=emailservice__pb2.Query.SerializeToString,
                response_deserializer=emailservice__pb2.Email.FromString,
                )
        self.SayHello = channel.unary_unary(
                '/emailservice.EmailService/SayHello',
                request_serializer=emailservice__pb2.HelloRequest.SerializeToString,
                response_deserializer=emailservice__pb2.HelloReply.FromString,
                )
        self.SayHelloAgain = channel.unary_unary(
                '/emailservice.EmailService/SayHelloAgain',
                request_serializer=emailservice__pb2.HelloRequest.SerializeToString,
                response_deserializer=emailservice__pb2.HelloReply.FromString,
                )


class EmailServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloAgain(self, request, context):
        """Sends another greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmail,
                    request_deserializer=emailservice__pb2.Query.FromString,
                    response_serializer=emailservice__pb2.Email.SerializeToString,
            ),
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=emailservice__pb2.HelloRequest.FromString,
                    response_serializer=emailservice__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloAgain': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHelloAgain,
                    request_deserializer=emailservice__pb2.HelloRequest.FromString,
                    response_serializer=emailservice__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emailservice.EmailService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmailService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emailservice.EmailService/GetEmail',
            emailservice__pb2.Query.SerializeToString,
            emailservice__pb2.Email.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emailservice.EmailService/SayHello',
            emailservice__pb2.HelloRequest.SerializeToString,
            emailservice__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHelloAgain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emailservice.EmailService/SayHelloAgain',
            emailservice__pb2.HelloRequest.SerializeToString,
            emailservice__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
